<a href="https://colab.research.google.com/github/navendu10/MLmodels_NB/blob/main/numpy1_nav.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e+3)
L2

[4, 5, 6, 7]

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e,f in zip(a, b):
  dot += e*f
dot

11

In [ ]:
np.sum(a*b)

11

In [ ]:
np.dot(a,b)

11

In [ ]:
a.dot(b)

11

In [ ]:
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

In [ ]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
new_var = np.trace(A)
new_var

5

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [ ]:
V[:,0] * Lam[0] , A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0] * Lam[0] , A @ V[:,0])

True

In [ ]:
A = np.array([[1,1], [1.5,4]])
b = np.array([2200, 5050])

In [ ]:
np.linalg.solve(A,b)

array([1500.,  700.])

In [ ]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.30022162994744683

In [ ]:
np.random.random((2,3))

array([[0.15969245, 0.66052946, 0.85278894],
       [0.69006747, 0.79000249, 0.29399173]])

In [ ]:
np.random.randn(2,3)

array([[-0.35370718,  0.07498982,  0.07004758],
       [ 1.18741637,  0.23583503,  1.48438565]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

0.013202812514680062

In [ ]:
np.mean(R)

0.013202812514680062

In [ ]:
np.var(R)

0.9862447041392716

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis = 0)

array([0.00676304, 0.01014744, 0.00219185])

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T)

array([[ 1.01453571, -0.01166957,  0.00368719],
       [-0.01166957,  0.99915215, -0.00636058],
       [ 0.00368719, -0.00636058,  0.9932457 ]])

In [ ]:
np.random.randint(0,10, size = (3,3))

array([[4, 9, 4],
       [8, 9, 4],
       [1, 0, 5]])